CREATE SEQUENCE TBL_BOOKS_seq;

CREATE TABLE IF NOT EXISTS TBL_BOOKS
(book_id BIGINT DEFAULT NEXTVAL ('TBL_BOOKS_seq') NOT NULL,
title VARCHAR(255) NOT NULL,
genre VARCHAR(20) NOT NULL,
author VARCHAR(40) NOT NULL,
isEnabled BOOLEAN NOT NULL,
PRIMARY KEY (book_id));


CREATE SEQUENCE TBL_USERS_seq;

CREATE TABLE IF NOT EXISTS TBL_USERS
(user_id BIGINT DEFAULT NEXTVAL ('TBL_USERS_seq') NOT NULL,
username VARCHAR(20) NOT NULL,
name VARCHAR(50) NOT NULL,
password VARCHAR(255) NOT NULL,
role VARCHAR(6) NOT NULL,
isEnabled BOOLEAN NOT NULL,
PRIMARY KEY (user_id));


CREATE TABLE IF NOT EXISTS TBL_LIBRARY
(user_id BIGINT NOT NULL,
book_id BIGINT NOT NULL,
FOREIGN KEY (book_id) REFERENCES TBL_BOOKS (book_id),
FOREIGN KEY (user_id) REFERENCES TBL_USERS (user_id));


CREATE TABLE IF NOT EXISTS TBL_RATING
(user_id BIGINT NOT NULL,
book_id BIGINT NOT NULL,
rating DOUBLE PRECISION NOT NULL,
FOREIGN KEY (book_id) REFERENCES TBL_BOOKS (book_id),
FOREIGN KEY (user_id) REFERENCES TBL_USERS (user_id));


CREATE TABLE IF NOT EXISTS TBL_RECENT
(user_id BIGINT NOT NULL,
book_id BIGINT NOT NULL,
readDate TIMESTAMP(0) DEFAULT current_date NOT NULL ,
FOREIGN KEY (book_id) REFERENCES TBL_BOOKS (book_id),
FOREIGN KEY (user_id) REFERENCES TBL_USERS (user_id));